export interface SocialMediaInfo {
  name: string;
  icon: [string, string];
  color: string;
}

export const socialMediaMap: Record<string, [string, string, string]> = {
  Facebook: ["fab", "facebook", "#1877F2"],
  Twitter: ["fab", "twitter", "#1DA1F2"],
  Instagram: ["fab", "instagram", "#E4405F"],
  LinkedIn: ["fab", "linkedin", "#0A66C2"],
  Reddit: ["fab", "reddit", "#FF4500"],
  YouTube: ["fab", "youtube", "#FF0000"],
  Pinterest: ["fab", "pinterest", "#BD081C"],
  Snapchat: ["fab", "snapchat", "#FFFC00"],
  WhatsApp: ["fab", "whatsapp", "#25D366"],
  TikTok: ["fab", "tiktok", "#000000"],
  Tumblr: ["fab", "tumblr", "#36465D"],
  Flickr: ["fab", "flickr", "#0063DC"],
  Vimeo: ["fab", "vimeo", "#1AB7EA"],
  Medium: ["fab", "medium", "#12100E"],
  GitHub: ["fab", "github", "#181717"],
  GitLab: ["fab", "gitlab", "#FC6D26"],
  Dribbble: ["fab", "dribbble", "#EA4C89"],
  Slack: ["fab", "slack", "#4A154B"],
  Skype: ["fab", "skype", "#00AFF0"],
  Zoom: ["fab", "zoom", "#2D8CFF"],
  Discord: ["fab", "discord", "#5865F2"],
  Mastodon: ["fab", "mastodon", "#3088D4"],
  Twitch: ["fab", "twitch", "#9146FF"],
  SoundCloud: ["fab", "soundcloud", "#FF8800"],
  DeviantArt: ["fab", "deviantart", "#05CC47"],
  VK: ["fab", "vk", "#4680C2"],
  Weibo: ["fab", "weibo", "#DF2029"],
  QQ: ["fab", "qq", "#12B7F5"],
  "Stack Overflow": ["fab", "stack-overflow", "#F58025"],
  Quora: ["fab", "quora", "#B92B27"],
  Yelp: ["fab", "yelp", "#D32323"],
  Meetup: ["fab", "meetup", "#ED1C40"],
  Goodreads: ["fab", "goodreads", "#372213"],
  Foursquare: ["fab", "foursquare", "#F94877"],
  "Last.fm": ["fab", "lastfm", "#D51007"],
  Spotify: ["fab", "spotify", "#1ED760"],
  Line: ["fab", "line", "#00C300"],
  Telegram: ["fab", "telegram", "#2CA5E0"],
  Badoo: ["fab", "badoo", "#783BF9"],
  Behance: ["fab", "behance", "#1769FF"],
  Ello: ["fab", "ello", "#000000"],
  Mix: ["fab", "mix", "#FF8126"],
  Periscope: ["fab", "periscope", "#40A4C4"],
  Xing: ["fab", "xing", "#006567"],
  Houzz: ["fab", "houzz", "#7AC142"],
  TripAdvisor: ["fab", "tripadvisor", "#34E0A1"],
  "Hacker News": ["fab", "hacker-news", "#FF6600"],
  AngelList: ["fab", "angellist", "#000000"],
  Trello: ["fab", "trello", "#0079BF"],
  Bandcamp: ["fab", "bandcamp", "#1DA0C3"],
  Etsy: ["fab", "etsy", "#F16521"],
  Vine: ["fab", "vine", "#00B488"],
  "500px": ["fab", "500px", "#0099E5"],
  Kickstarter: ["fab", "kickstarter", "#05A06A"],
  "Sina Weibo": ["fab", "weibo", "#DF2029"],
  Viber: ["fab", "viber", "#7360F2"],
  Odnoklassniki: ["fab", "odnoklassniki", "#EE8208"],
  Renren: ["fab", "renren", "#005EAC"],
  Zhihu: ["fab", "zhihu", "#0084FF"],
  Yammer: ["fab", "yammer", "#0072C6"],
  // Add more as needed
};
